name: maven test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt 
    - name: Build with Maven
      run: |
        mvn archetype:generate -DinteractiveMode=false  -DgroupId=test -DartifactId=test3 -DarchetypeArtifactId=maven-archetype-webapp
        cd test3
        mvn install    
  scp:
    name: scp
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source:  deploy.tar
        target: /usr/local/bin/apache-tomcat-9.0.69/webapps
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: scp
    steps:
    - name: ssh 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: 
          tar -xvf /usr/local/bin/apache-tomcat-9.0.69/webapps/deploy.tar .
          ls -al /usr/local/bin/apache-tomcat-9.0.69/webapps/
          bash /usr/local/bin/apache-tomcat-9.0.69/bin/startup.sh
